### ISSUE TITLE
Update app to SDK v3 (Homey 5.0.0)

### ISSUE THREAD

**Issue by aivus** [aivus/com.gree#58]
Need to prepare PR to update existing codebase for Homey's SDK v3

Documentation: https://apps-sdk-v3.developer.athom.com/tutorial-SDK%20Changelog.html

Additional items:
- [x] Update usage of [node-homey-log](https://github.com/athombv/node-homey-log) for SDKv3

**Comment by aivus** [comment]
As the app is working fine using SDKv2 for Homey 5.0, update to SDKv3 will be postponed.

**Comment by aivus** [comment]
Hey folks 👋 

I would ask you to help me with releasing version with SDKv3 support.
Right now I don't have an access to my AC and because of this cannot test the update properly.

If you are still using this app and have Homey with firmware version 5, please install the test version of the app and use it for several days.

If something will not work I'll try to fix it and push the fix to the "test" pipeline ASAP. All possible crash reports will be reviewed within a day.

Link to the test version with SDKv3 support (Homey v5 only)
https://homey.app/en-us/app/com.gree/Gree/test/

Thanks a lot

/cc @denniedegroot @grunci @jahnkenneth @witmannmark @lucasvdh @zawinull

**Comment by lucasvdh** [comment]
Updated to the latest test version of the app but the device stays marked as unavailable. 

This might be due to my home network because I still use Ubiquity and they have not fixed their mDNS reflector (https://github.com/aivus/com.gree/pull/52) and my AC-unit is on a different vlan. 

When attempting to re-add the device via the Gree Android app I found out that the app isn't working for me at the moment. Might be having issues with a 2.4 and 5Ghz network with the same name .. I'll try and debug once I've got some time.

**Comment by denniedegroot** [comment]
Running the test version and everything still seems to work.

**Comment by zawinull** [comment]
The test version seems to be working fine.

**Comment by aivus** [comment]
Thank you all. I've released this version.

**Comment by aivus** [comment]
@lucasvdh I believe you are experiencing the same as in #52
